//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosyalar
    {
        public int DosyaId { get; set; }
        public int PersonelId { get; set; }
        public string DosyaYolu { get; set; }
        public Nullable<System.DateTime> YüklenmeTarihi { get; set; }
        public string DosyaTuru { get; set; }
        public string DosyaAdi { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
