//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsGecmisi
    {
        public int IsID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public string FirmaAdi { get; set; }
        public string Pozisyon { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
