//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProjesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IKProjectEntities : DbContext
    {
        public IKProjectEntities()
            : base("name=IKProjectEntities")
        {
            this.Configuration.LazyLoadingEnabled = true;  
            this.Configuration.ProxyCreationEnabled = true;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dosyalar> Dosyalar { get; set; }
        public virtual DbSet<IsGecmisi> IsGecmisi { get; set; }
        public virtual DbSet<OkulBilgileri> OkulBilgileri { get; set; }
        public virtual DbSet<Personeller> Personeller { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
