//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OkulBilgileri
    {
        public int OkulId { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public string OkulAdi { get; set; }
        public string BolumAdi { get; set; }
        public Nullable<int> MezuniyetYili { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
